substitutions:
  node_name: ESP32-C3-DevKitC-02
  static_ip: 192.168.1.53

packages:
  esp32c3: !include common/esp32c3.yaml
  remote_package:
    url: https://github.com/jwillikers/esphome-static-network
    ref: main
    file: static_network.yaml

esphome:
  name: ${node_name}

logger:

api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_name} Fallback Hotspot"
    password: !secret fallback_ap_password

# captive_portal:

# light:
#   - platform: neopixelbus
#     variant: WS2812
#     pin: GPIO8
#     type: BGR
#     num_leds: 1
#     name: "Onboard RGB LED"
#     effects:
#       - random:
#       - pulse:
#       - strobe:
#       - flicker:

i2c:
  sda: GPIO4
  scl: GPIO5

sensor:
  - platform: bme680
    address: 0x77
    temperature:
      name: "Temperature"
      oversampling: 16x
    pressure:
      name: "Pressure"
    humidity:
      name: "Humidity"
      id: humidity
    gas_resistance:
      name: "Gas Resistance"
      id: gas_resistance
# - platform: template
#   name: "Indoor Air Quality"
#   id: iaq
#   unit_of_measurement: IAQ
#   lambda: 'return log(id(gas_resistance).state) + 0.04 * id(humidity).state;'
